### ISSUE TITLE
Permission to write to external storage not granted

### ISSUE THREAD

**Issue by Elinvention** [AICP/packages_apps_AICP_OTA#8]
When I try to download an update this toast notification shows up and prevents me from downloading the update. I have no external sd card, but enough internal space. Is this a technical limitation of Android?

**Comment by LorDClockaN** [comment]
Grant permission in settings/apps/aicpota

**Comment by Elinvention** [comment]
Right... Thank you.

**Comment by Morteza-A90** [comment]
hi. i have a problem . in settings/apps/aicpota
permission section is disable .. 

Permissions
(no permissions requested )
